# Generated by Django 4.1.1 on 2023-08-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PI_hospital', '0002_pat_dischargedetail_patient_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='App_Confirmation',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pat_dischargedetail',
            name='Patient_email',
            field=models.EmailField(default='', max_length=30),
        ),
    ]
